# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
    issue_comment:
        types: [created]

jobs:
    comment:
        if: github.event.sender.type != 'Bot' && github.event.comment.body == '/comment'
        runs-on: ubuntu-latest

        permissions:
            issues: write
            pull-requests: write
            contents: write

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Add a comment to the PR
              run: gh pr comment ${{ github.event.pull_request.number }} --body "Uh oh, the tests failed!"
